<a href="https://colab.research.google.com/github/dahiya-04/pytorch_from_basic/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.6.0+cu124'

In [ ]:
scalar = torch.tensor(6)
print(scalar.ndim)
print(scalar.item())

0
6


In [ ]:
#vector is a single dimension tensor but can contain many numbers
vector = torch.tensor([1,2,3])
print(vector.ndim)
print(vector.shape)

1
torch.Size([3])


In [ ]:
#Matrix are collection vectors and have dimension two
Matrix = torch.tensor([[7,8],[3,5]])
print(Matrix.ndim)
print(Matrix.shape)

2
torch.Size([2, 2])


In [ ]:
#Tensor can represent almost everything , they usually have dimension greater than two
Tensor = torch.tensor([[[2,3,4],[4,5,6],[4,5,6]]])
print(Tensor.ndim)
print(Tensor.shape)

3
torch.Size([1, 3, 3])


In [ ]:
# creating random tensor of size(3,4)
random_tensor = torch.rand(size=(2,3,4))
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[[0.7059, 0.6641, 0.5923, 0.8195],
         [0.0427, 0.3773, 0.6167, 0.3328],
         [0.8520, 0.8711, 0.4271, 0.4352]],

        [[0.0258, 0.9220, 0.8378, 0.8619],
         [0.0358, 0.6151, 0.4622, 0.1235],
         [0.7600, 0.3102, 0.9674, 0.7307]]])
3
torch.Size([2, 3, 4])


In [ ]:
zero = torch.zeros(size=(1,3,4))
print(zero)
print(zero.ndim)
print(zero.shape)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
3
torch.Size([1, 3, 4])


In [ ]:
#Creating a range and tensors like
zero_to_ten = torch.range(start=0,end=10,step=1)
print(zero_to_ten)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


<ipython-input-18-3636050311>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten = torch.range(start=0,end=10,step=1)


In [ ]:
#Tensor Datatypes
#Some tensors are good for CPU and GPU
# torch.coda is for GPU
float_32_tensor = torch.tensor([3.0,4.0,9.0],
                               dtype = None
                               ,device =None
                               ,requires_grad=False)
float_32_tensor.shape,float_32_tensor.dtype,float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0,4.0,9.0],
                               dtype = torch.float16
                               ,device =None
                               ,requires_grad=False)
float_16_tensor.shape,float_16_tensor.dtype,float_16_tensor.device

(torch.Size([3]), torch.float16, device(type='cpu'))

In [ ]:
#Manipulation tensors(tensor operatons)
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor = tensor -10
tensor.shape

torch.Size([3])

In [ ]:
#torch.matmul()
%%time
torch.matmul(tensor,tensor)

CPU times: user 2.13 ms, sys: 5 µs, total: 2.14 ms
Wall time: 8.67 ms


tensor(4334)

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.matmul(tensor_A.T,tensor_B)

tensor([[ 76, 103],
        [100, 136]])

In [ ]:
#torch.nn.Linear()
import torch
import torch.nn as nn

# Define a linear layer with 5 input features and 10 output features
linear_layer = nn.Linear(in_features=5, out_features=10)

# Create some dummy input data with a batch size of 2
# The input tensor shape should be (batch_size, in_features)
input_data = torch.randn(2, 5)

# Apply the linear transformation
output_data = linear_layer(input_data)

# Print the shape of the output
print(output_data.shape)

torch.Size([2, 10])


In [ ]:
x =torch.arange(1.,10.)
x,x.shape
z = x.view(1,9)
z=z.shape
print(z)
print(x.shape)

torch.Size([1, 9])
torch.Size([9])


In [ ]:
x_original = torch.rand(size=(224,224,3))
x_permute = x_original.permute(2,0,1)
print(x_original.shape)
print(x_permute.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [ ]:
#indexing (selecting data from tensor)
x = torch.arange(1,10).reshape(1,3,3)
print(x,x.shape)

print(x[0])
print(x[0,0])
print(x[0,0,0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [2]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)
random_tensor_A == random_tensor_b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [1]:
!nvidia-smi


Mon Jun 16 11:44:39 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   59C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
#getting Pytorch to run on GPU
import torch
torch.cuda.is_available()

True

In [3]:
#varaible to use GPU if available
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
#PUTTING TENOSRS (and models) on CPU
tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [5]:
#Moving tensors back to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])